
INSERT INTO CATALOGS(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES ('CATALOG-0001', 'Berlin', 100, 1500);
INSERT INTO CATALOGS(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES ('CATALOG-0002', 'Tokyo', 100, 900);
INSERT INTO CATALOGS(PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
VALUES ('CATALOG-0003', 'Newyork', 100, 1200);